#!/bin/bash
if [[ "$1" == "" ]]; then
  echo "usage: partition-memory-stick <device>"
  echo "       eg partition-memory-stick sdb"
  echo "WARNING: This script proceeds without asking any questions."
  echo "         If you use it on the wrong disk you will trash the partition table"
  echo "         and probably lose all your data."
  exit
fi
device=$1

# Do check if the disk is mounted anywhere
mounts=`mount | grep /dev/$device | wc -l`
if [[ $mounts != 0 ]]; then
  echo "That disk is mounted. Unmounting."
  for i in 1 2 3 4; do
    if [ -e /dev/${device}${i} ]; then
      echo "Unmounting ${device}${i}"
      umount /dev/${device}${i}
    fi
  done
fi

if [ ! -e /dev/$device ]; then
  echo "/dev/$device doesn't exist."
  exit
fi

mkfs.vfat /dev/${device}1 -n dos
mkfs.ext4 /dev/${device}2 -L serval
mkfs.ext4 /dev/${device}3 -L serval-var

echo
echo
echo
echo "All done.  USB memory stick now ready for use in a mesh extender."
