#!/bin/bash

if [ ! -e captive-portal ]; then
  git clone https://github.com/cvirieux/servalProject captive-portal
  ln -sf ../../../captive-portal/www serval-dna/files/serval/www
else
  cd captive-portal
  git pull
  cd ..
fi


